name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # Separate job to check lock file integrity
  lock-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Check lock file is up to date
      run: uv lock --check

  # Main test job with matrix for multiple Python versions
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync

    - name: Lint and format check
      run: |
        uv run ruff check
        uv run ruff format --check

    - name: Security checks
      run: |
        uv run ruff check . --select=S --ignore=S603,S607
        uv run pip-audit

    - name: Run tests
      run: |
        uv run pytest --cov=. --cov-report=term-missing --cov-report=xml

    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      if: matrix.python-version == '3.12'
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella


  # Note: Security checks are now integrated into the main test job via ruff + pip-audit